export enum errorTypeEnum {
    INPUT_VALIDATION_ERROR = 400,
    DB_OPERATION_ERROR = 500,
    UNATHORIZED_ERROR = 401,
    UNKNOWN_ERROR = 500,
    DUPLICATE_ENTRY_ERROR = 406,
    NOT_FOUND_ERROR,
    DATABASE_ERROR,
    INTERNAL_SERVER_ERROR,
    NOT_FOUND,
    UNAUTHORIZED,
    INVALID_INPUT_ERROR,
    AUTH_ERROR
}
